name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.8.1
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=3.16.8"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cached_video_player_plus: ^2.0.0
  wakelock_plus: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
